### ISSUE TITLE
Analizar una posible reestructura de directorios

### ISSUE THREAD

**Issue by mvarela92** [Bantotal/WBBancoDelta#115]
Analizar una posible reestructura de directorios, para poder tener bien organizados los components de presentación y los components containers.

Revisar si es necesario o no, ver como se hace en otros proyectos, etc.

Gracias.

**Comment by Rojazefi** [comment]
@mvarela92 luego de conversar acordamos lo siguiente : https://docs.google.com/document/d/1Y10pCwZcFUB9iAk1TZjRZg9RlhhinHEbKRBPzfnxp4s/edit?usp=sharing

**Comment by mvarela92** [comment]
@Rojazefi excelente! Me gustó mucho.

Lo único que capaz cambiaría es en atributos(atomos), pasar atributos y crearía otro que se llame functions, para las funciones que le llegan. Así queda bien separado...

Que les parece?

**Comment by mvarela92** [comment]
@Rojazefi pasé este issue a in progress

**Comment by wilcus** [comment]
@mvarela92 . Se puede cambiar el nombre de 'functions' a 'events'?

**Comment by Rojazefi** [comment]
ok @mvarela92 hablando aquí con los muchachos les pareció bien adicionar  'functions' para las funciones que les lleguen a los atomos

**Comment by mvarela92** [comment]
Genial, entonces podemos reestructurar eso y documentarlo? 

Gracias @Rojazefi

**Comment by wilcus** [comment]
Algo asi @mvarela92 ? 

```javascript
var attributes = {'className': 'something', ..}
var functions = {'onClick': () => {}, ...}

<Button attributes={atrributes} functions={functions}/>
```

Viendolo asi como que parece mejor cambiar los nombres de 'functions' a 'events'. Que opinas?

**Comment by mvarela92** [comment]
Si, me parece mejor si @wilcus, excelente.

Si la doc en el readme si.

Gracias.
