### ISSUE TITLE
Componentes de imagen

### ISSUE THREAD

**Issue by mvarela92** [Bantotal/WBBancoDelta#121]
El componente de imagen debe soportar recibir un recurso estático el cual se encuentra público o un string base64 para imágenes privadas provenientes del backend.

**Comment by wilcus** [comment]
@mvarela92 como esta ahora si lo soporta

https://github.com/Bantotal/WBBancoDelta/blob/development/src/components/atoms/Image.js#L6

**Comment by mvarela92** [comment]
@wilcus genial cerramos entonces
