### ISSUE TITLE
Buenas practicas, de wiki a readme

### ISSUE THREAD

**Issue by mvarela92** [Bantotal/WBBancoDelta#64]
@wilcus te animas a pasar lo de la wiki al readme del proyecto.

El wiki es mas bien para documentar las entregas. Mas adelante el banco nos va a pedir fechas de entrega y van a ir ahí. El readme es mas para nosotros, los que trabajamos en el desarrollo.

Crea una sección nueva Tips o Buenas Practicas y ponlo ahí.

Muchas gracias

**Comment by wilcus** [comment]
Ok :+1:

**Comment by wilcus** [comment]
@mvarela92 puedo mandarlo directo al master?

**Comment by mvarela92** [comment]
Gracias
