### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by mvarela92** [Bantotal/WBBancoDelta#99]
definir como se van a testear los componentes y los reducers

**Comment by wilcus** [comment]
Aquí podría agregarse la configuración de travis como lo agregue en mi repo https://github.com/wilcus/react-prueba/pull/34 ?
Pero además seria necesario que tu habilites el servicio en https://travis-ci.org/  porque solo el creador del repositorio tiene los permisos

**Comment by mvarela92** [comment]
@wilcus genial, lo que veo es que si el repo es privado, son 129 dolares al mes no?

**Comment by wilcus** [comment]
@mvarela92  Si correcto o otro plan si prefieres https://travis-ci.com/plans

**Comment by mvarela92** [comment]
@wilcus okey, entonces en primera instancia, vamos a correr los test nosotros a mano desde la consola. Luego vemos si pagamos el plan para hacerlo directamente aquí. Gracias por la info

**Comment by mvarela92** [comment]
Gracias
